logging:
  level:
    org:
      springframework: OFF
    maersk:
      com: INFO
application:
  save:
    metrics:
     required: false
     filename: c:\Users\mickm\eclipse-workspace\mq-metrics\mq-metrics\mySavedMetrics.json
spring:
  main:
    banner-mode: CONSOLE
  banner:
    location: banner.txt     
  security:
    user:
      name: monitor
      password: monitor123                  
ibm:
  mq:
    multiInstance: false
    queueManager: QMAP01
    channel: MQ.MONITOR.SVRCONN
    connName: localhost(1501)
    sslCipherSpec: TLS_RSA_WITH_AES_256_CBC_SHA256
    sslCipherSpec1: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
    useSSL: true
    user: MQmon01
    password: Passw0rdPassw0rd1234
    authenricateUsingCSP: true
    local: false
    keepMetricsWhenQueueManagerIsDown: false
    clearMetrics: 5
# accounting / statistics, pcf values, browse true/false - false will delete records
    pcf:
      accountingType1: MQCFT_STATISTICS
      parameters: MQIAMO_PUT_MAX_BYTES, MQIAMO_GET_MAX_BYTES, MQIAMO_PUTS, MQIAMO_GETS, MQIAMO_GETS_FAILED, MQIAMO_PUTS_FAILED
      browse: false
      period:
# Collection time periods
         collections: DAYS, MONTHS, YEARS
# filter on date / time periods      
         start: 
         end: 
    json:
      sort: true
      order: ascending
# filter queues    
    objects:
      queues:
        include: "*"
        exclude: SYSTEM.,AMQ.,DUMMY,RFHUTIL.,ERROR.HANDLER
    event:
      delayInMilliSeconds: 10000      
    security:
      truststore: C:\ProgramData\IBM\MQ\qmgrs\QMAP01\ssl\qmap01jks.jks
      truststore-password: Passw0rd
      keystore: C:\ProgramData\IBM\MQ\qmgrs\QMAP01\ssl\qmap01jks.jks
      keystore-password: Passw0rd
management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus      
  endpoint:
    health:
      show-details: always        
  security:
    enabled: false
info:
  app:
    name: MQ-Monitor
    description: IBM MQ Monitor
    version: 1.0.0.0
    java:
      version: 1.8.0.0
server:
  port:
    8081